---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Load variables
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml
    - name: Configure ipp-crypto examples
      ansible.builtin.command:
        cmd: "cmake CMakeLists.txt -B_build -DARCH={{ ippcp_arch }} -DMERGED_BLD:BOOL=ON -DBUILD_EXAMPLES:BOOL=ON"
        chdir: "{{ ippcp_checkout_path }}/examples"
      become: true
      changed_when: true
    - name: Compile ipp-crypto examples
      ansible.builtin.command:
        cmd: "cmake --build _build --parallel {{ num_build_jobs }}"
        chdir: "{{ ippcp_checkout_path }}/examples"
      become: true
      changed_when: true
